### ISSUE TITLE
Download

### ISSUE THREAD

**Issue by dragopro49** [AtomSponge/Hosencorp#71]
Moin Schwamm,

habe das Problem, dass die installation der Bibliotheken nach 33% abbricht und danach der Download neu gestartet werden muss.

In der Konsole wird folgendes angeeigt:
B#208] Download of http://crafatar.com/avatars/837ccbad2db94241a6599c76e4cd52cd?size=100&helm Failed!
[B#208] Starting download of http://crafatar.com/avatars/837ccbad2db94241a6599c76e4cd52cd?size=100&helm, with 1 tries remaining
[B#208] Download of http://crafatar.com/avatars/837ccbad2db94241a6599c76e4cd52cd?size=100&helm Failed!
[B#208] Error downloading user face image: dragopro49
[B#208] Download of http://crafatar.com/avatars/837ccbad2db94241a6599c76e4cd52cd?size=100&helm Failed!
[B#208] Error downloading user face image: dragopro49
[B#208] Analytics Response [installModpack]: 200
[B#208] Starting download of http://files.minecraftforge.net/maven/org/scala-lang/scala-compiler/2.10.2/scala-compiler-2.10.2.jar, with 3 tries remaining
[B#208] Analytics Response [installModpack]: 200

**Comment by AtomSponge** [comment]
So ein kleiner Ausschnitt hilft wenig, sieht aber danach aus, als ob Crafatar nicht erreichbar war oder Ähnliches.
