### ISSUE TITLE
Weltgenerator

### ISSUE THREAD

**Issue by Achura1221** [AtomSponge/Hosencorp#78]
ich habe einen Nitrado server wo das Hosencorp modpack drauf läuft es geht auch alles nur der Weltgenerator funktioniert nicht hoffe du kannst mir helfen :D

**Comment by AtomSponge** [comment]
In den server.properties ```level-type``` auf ```BIOMESOP``` umstellen und den Server neustarten. Die schon generierte Welt muss vorher gelöscht werden, da sonst natürlich keine neue generiert wird.
