### ISSUE TITLE
Modpack startet nicht

### ISSUE THREAD

**Issue by AtomSponge** [AtomSponge/Hosencorp#79]
@Stupnix, 28. Feb. 2015 17:45 MEZ:
> Hab' ein ähnliches Problem: Modpack wird runter geladen, startet aber nicht. Es gibt keine Fehlermeldung. Der Launcher schließt sich und öffnet sich kurz danach wieder. Passiert aber nur bei dem ModPack.

**Comment by AtomSponge** [comment]
Welche Java-Version hast du installiert?
(Das neue Modpack kommt übrigens eh bald :wink:)

**Comment by Stupnix** [comment]
JRE ist Version 7. Minecraf Java Version im den Launcher-Optionen ist auf Standard, also 1.8.0_31.

**Comment by AtomSponge** [comment]
Wenn die Java Version 1.8.0_31 im Launcher eingestellt ist, nutzt der auch Java 8. Falls du eine Java 7 jre/jdk installiert hast, versuch mal diese im Launcher auszuwählen

**Comment by Stupnix** [comment]
Jupp, hab noch eine ältere und es funktioniert! Danke! : )

**Comment by AtomSponge** [comment]
Super!
